// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiRR-2FGRZjEqnG4YpKpDE6kfnthVcUhs',
    appId: '1:777312543699:web:9daa874fee647c09a9c526',
    messagingSenderId: '777312543699',
    projectId: 'e-book-dd2a6',
    authDomain: 'e-book-dd2a6.firebaseapp.com',
    storageBucket: 'e-book-dd2a6.appspot.com',
    measurementId: 'G-J3S4Z517QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk8WB2OXUM2yv7IItN2Zx0K0Jos8WiuYs',
    appId: '1:777312543699:android:3453e01c5b2388b7a9c526',
    messagingSenderId: '777312543699',
    projectId: 'e-book-dd2a6',
    storageBucket: 'e-book-dd2a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQhp2LJokZVXqXKCU_Hsb8pukfWymSFII',
    appId: '1:777312543699:ios:d309f990b4b1539fa9c526',
    messagingSenderId: '777312543699',
    projectId: 'e-book-dd2a6',
    storageBucket: 'e-book-dd2a6.appspot.com',
    iosBundleId: 'com.example.lithabit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQhp2LJokZVXqXKCU_Hsb8pukfWymSFII',
    appId: '1:777312543699:ios:d309f990b4b1539fa9c526',
    messagingSenderId: '777312543699',
    projectId: 'e-book-dd2a6',
    storageBucket: 'e-book-dd2a6.appspot.com',
    iosBundleId: 'com.example.lithabit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiRR-2FGRZjEqnG4YpKpDE6kfnthVcUhs',
    appId: '1:777312543699:web:6a103d5de155501ba9c526',
    messagingSenderId: '777312543699',
    projectId: 'e-book-dd2a6',
    authDomain: 'e-book-dd2a6.firebaseapp.com',
    storageBucket: 'e-book-dd2a6.appspot.com',
    measurementId: 'G-5HLFFJ2CFQ',
  );
}
